### ISSUE TITLE
Play / Stop Button Style

### ISSUE THREAD

**Issue by BitterSymphony** [viezel/AudioPlayerWidget#1]
Really cool stuff as always :)
Btw Is it possible to change the button style, like backgroundImage of button or sth ?

**Comment by viezel** [comment]
you can overwrite the styles like this:

```
// alloy
Alloy.Globals.fontAwesome = new IconicFont({ font: 'FontAwesome' });
Alloy.Globals.icons = {};
Alloy.Globals.icons.play = Alloy.Globals.fontAwesome.icon('fa-play');
Alloy.Globals.icons.pause = Alloy.Globals.fontAwesome.icon('fa-pause');
Alloy.Globals.icons.stop = Alloy.Globals.fontAwesome.icon('fa-stop');
```

and in tss:

```
"#audioPlayer":{
    styles:{        
        playStopBtn: {
            color: "red"
        },  
        scrubBar: {
            tintColor: "red"
        }
    playIcon: Alloy.Globals.icons.play,
    pauseIcon: Alloy.Globals.icons.pause
}
```

**Comment by BitterSymphony** [comment]
Sorry, I mean using my own image files instead of font awesome icons, since FontAwesome font may not be able to display properly in some android devices here. Could you please help me out :) ?

**Comment by viezel** [comment]
you will have to change the widget.

**Comment by BitterSymphony** [comment]
Ok. Will look into it :). Tks for ur kind assistance.
